[pytest]
# Command line arguments
# --headed: Run tests in headed mode
# --browser: Default browser
# --slowmo: Add delay in ms between actions (good for debugging)
; addopts = --headed --browser chromium --screenshot on --html=report.html --self-contained-html
addopts = --headed --browser chromium --slowmo 500 -s

# Directories to search for tests
testpaths = tests

# Forces pytest to only look for classes starting with 'Test'
python_files = test_*.py

# Forces pytest to only look for methods starting with 'test_'
python_functions = test_*
# Markers for categorizing tests (Sanity, Regression, etc.)
markers =
    smoke: Quick check of critical functionality
    regression: Full suite testing
    sanity: Basic health check of the build